package main

import (
	"aoc2025/solutions"
	"fmt"
	"time"
)

func main() {
	fmt.Println()
	start := time.Now()
	print("Day One Part One: ")
	solutions.Day_one_part_one()
	print("Day One Part Two: ")
	solutions.Day_one_part_two()
	print("Day Two Part One: ")
	solutions.Day_two_part_one()
	print("Day Two Part Two: ")
	solutions.Day_two_part_two()
	print("Day Three Part One: ")
	solutions.Day_three_part_one()
	print("Day Three Part Two: ")
	solutions.Day_three_part_two()
	print("Day Four Part One: ")
	solutions.Day_four_part_one()
	print("Day Four Part Two: ")
	solutions.Day_four_part_two()
	print("Day Five Part One: ")
	solutions.Day_five_part_one()
	print("Day Five Part Two: ")
	solutions.Day_five_part_two()
	print("Day Six Part One: ")
	solutions.Day_six_part_one()
	print("Day Six Part Two (Test Answer): ")
	solutions.Day_six_part_two()
	// print("Day Seven Part One: ")
	solutions.Day_seven_part_one()
	// Converted the day 7 solution into one function to try to optimize for time
	// print("Day Seven Part Two: ")
	// solutions.Day_seven_part_two(passed_lines)
	print("Day Eight Part One: ")
	solutions.Day_eight_part_one()
	print("Day Eight Part Two: ")
	solutions.Day_eight_part_two()
	print("Day Nine Part One: ")
	solutions.Day_nine_part_one()
	print("Day Nine Part Two: ")
	solutions.Day_nine_part_two()
	print("Day Ten Part One: ")
	solutions.Day_ten_part_one()
	print("Day Ten Part Two: ")
	solutions.Day_ten_part_two()
	print("Day Eleven Part One: ")
	solutions.Day_eleven_part_one()
	print("Day Eleven Part Two: ")
	solutions.Day_eleven_part_two()
	print("Day Twelve Part One: ")
	solutions.Day_twelve_part_one()
	print("Day Twelve Part Two: ")
	solutions.Day_twelve_part_two()
	print("Day Thirteen Part One: ")
	solutions.Day_thirteen_part_one()
	print("Day Thirteen Part Two: ")
	solutions.Day_thirteen_part_two()
	print("Day Fourteen Part One: ")
	solutions.Day_fourteen_part_one()
	print("Day Fourteen Part Two: ")
	solutions.Day_fourteen_part_two()
	print("Day Fifteen Part One: ")
	solutions.Day_fifteen_part_one()
	print("Day Fifteen Part Two: ")
	solutions.Day_fifteen_part_two()
	print("Day Sixteen Part One: ")
	solutions.Day_sixteen_part_one()
	print("Day Sixteen Part Two: ")
	solutions.Day_sixteen_part_two()
	print("Day Seventeen Part One: ")
	solutions.Day_seventeen_part_one()
	print("Day Seventeen Part Two: ")
	solutions.Day_seventeen_part_two()
	print("Day Eighteen Part One: ")
	solutions.Day_eighteen_part_one()
	print("Day Eighteen Part Two: ")
	solutions.Day_eighteen_part_two()
	print("Day Nineteen Part One: ")
	solutions.Day_nineteen_part_one()
	print("Day Nineteen Part Two: ")
	solutions.Day_nineteen_part_two()
	print("Day Twenty Part One: ")
	solutions.Day_twenty_part_one()
	print("Day Twenty Part Two: ")
	solutions.Day_twenty_part_two()
	print("Day Twenty One Part One: ")
	solutions.Day_twentyone_part_one()
	print("Day Twenty One Part Two: ")
	solutions.Day_twentyone_part_two()
	print("Day Twenty Two Part One: ")
	solutions.Day_twentytwo_part_one()
	print("Day Twenty Two Part Two: ")
	solutions.Day_twentytwo_part_two()
	print("Day Twenty Three Part One: ")
	solutions.Day_twentythree_part_one()
	print("Day Twenty Three Part Two: ")
	solutions.Day_twentythree_part_two()
	print("Day Twenty Four Part One: ")
	solutions.Day_twentyfour_part_one()
	print("Day Twenty Four Part Two: ")
	solutions.Day_twentyfour_part_two()
	print("Day Twenty Five Part One: ")
	solutions.Day_twentyfive_part_one()
	print("Day Twenty Five Part Two: ")
	solutions.Day_twentyfive_part_two()
	fmt.Println()
	end := time.Now()
	fmt.Println(end.Sub(start))
}
